// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1VFHmry3tMYqITwCKsFgDv9CVVVKHpCA',
    appId: '1:275989232116:web:6df727ae5c4499ce5d61a1',
    messagingSenderId: '275989232116',
    projectId: 'fintech-fcc13',
    authDomain: 'fintech-fcc13.firebaseapp.com',
    storageBucket: 'fintech-fcc13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjWdek8bhYRHp9FjYmngSQxLu0tsVSh2k',
    appId: '1:275989232116:android:1af31b8b50e0863c5d61a1',
    messagingSenderId: '275989232116',
    projectId: 'fintech-fcc13',
    storageBucket: 'fintech-fcc13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcfg3xDqV6OQYXlqr74EFh37EEChPrynE',
    appId: '1:275989232116:ios:7ee295979afc390c5d61a1',
    messagingSenderId: '275989232116',
    projectId: 'fintech-fcc13',
    storageBucket: 'fintech-fcc13.appspot.com',
    iosBundleId: 'com.example.fintech',
  );
}
